#!/usr/bin/env python2

import time
from kobunsupport import load_config, handshake, read_line, write_line

handshake("auto-join to channels")

config = load_config()

while True:
    server, prefix, command, args = read_line()

    if command == "376":
        for channel in config["servers"][server]["channels"]:
            write_line(server, "JOIN", [channel])
            time.sleep(0.5)

        if "nickpass" in config["servers"][server]:
            write_line(server, "PRIVMSG", ["NickServ", "IDENTIFY {}".format(config["servers"][server]["nickpass"])])

# vim: set ts=4 sw=4 sta et sts=4 ai:
