#!/usr/bin/env python2

from kobunsupport import load_config, handshake, read_line, write_line

import random
import regex
import string

from hyphenator import Hyphenator

h = Hyphenator("/usr/share/myspell/dicts/hyph_en_US.dic")

handshake("butt")

config = load_config()



def buttify(s):
    choices = list(h.iterate(s))
    if not choices:
        return None
    l, r = random.choice(choices)
    rwords = r.split(" ")
    rwords[0] = "butt"
    return l + " ".join(rwords)

while True:
    server, prefix, command, args = read_line()

    if command.lower() == "privmsg":
        target, msg = args
        if random.randint(1, 100) > 2: continue

        m = buttify(msg)
        if m is None: continue

        write_line(server, "PRIVMSG", [target, m.encode("utf-8")])
