#!/usr/bin/env python2
# encoding: utf-8

from kobunsupport import load_config, handshake, read_line, write_line

import random

handshake("erryday i'm gfacing")

config = load_config()


RESPONSES = {
    "gface":    u"( ≖‿≖)",
    "cool":     u"COOL LIKE SNOWMAN ☃",
    "chownface":u"( ´· ‿ ·`)",
    "le-spj-face.jpg": "http://dl.dropbox.com/u/2880866/le-spj-face.jpg",
    "le-kobun-face.jpg": "http://dl.dropbox.com/u/2880866/le-kobun-face.jpg",
    "http://25.media.tumblr.com/tumblr_m5n4y9l4mw1ryt8iao4_1280.jpg": "NuclearPoweredKimJongIl is a faggot."
}

while True:
    server, prefix, command, args = read_line()

    if command.lower() == "privmsg":
        target, msg = args

        cands = []
        for cand, repl in RESPONSES.iteritems():
            if cand in msg:
                cands.append(repl)

        if cands:
            write_line(server, "PRIVMSG", [target, random.choice(cands).encode("utf-8")])

