#!/usr/bin/env python2

from kobunsupport import load_config, handshake, read_line, write_line

import subprocess

handshake("only useful service")

config = load_config()

while True:
    server, prefix, command, args = read_line()

    if command.lower() == "privmsg":
        target, msg = args

        parts = msg.split(" ", 1)

        if parts[0].lower() == "!djinn" and len(parts) == 2:
            _, what = parts
            out = subprocess.Popen(["./djinn",
                              "/dev/stdin"],
                             stdin=subprocess.PIPE,
                             stdout=subprocess.PIPE,
                             stderr=subprocess.STDOUT
                            ).communicate(what.replace(';', '\n'))[0].strip().split("\n")
            write_line(server, "PRIVMSG", [target, "\x02Djinn:\x02 " + '; '.join(out[1:])])
