#!/usr/bin/env python2
# encoding: utf-8

from kobunsupport import load_config, handshake, read_line, write_line

import binascii
import time

handshake("you are going to die alone")

with open("fortunes") as f:
    OPTIONS = f.read().split("\n")

config = load_config()

while True:
    server, prefix, command, args = read_line()

    if command.lower() == "privmsg":
        target, msg = args

        if msg.lower().strip() == "!fortune":
            write_line(server, "PRIVMSG", [target, "\x02Your fortune for today is:\x02 {}".format(
                OPTIONS[(binascii.crc32(prefix.lower()) + int(time.time() // (60 * 60 * 24))) % len(OPTIONS)]
            )])

