#!/usr/bin/env python2

from kobunsupport import load_config, handshake, read_line, write_line

import nltk

handshake("le reddit xD")

config = load_config()

def redditify(s):
    out = []

    for word, tag in nltk.pos_tag(nltk.word_tokenize(s)):
        if tag == 'DT': continue
        if tag in ('NN', 'NNP', 'JJ'): out.append('le')
        out.append(word)

    return ' '.join(out) + ' xD'

last_lines = {
}

while True:
    server, prefix, command, args = read_line()

    if command.lower() == "privmsg":
        target, msg = args

        parts = msg.split(" ", 1)

        if parts[0].lower() == "!reddit":
            if len(parts) == 2:
                what = parts[1]
            else:
                what = last_lines.get((server, target), "")

            what = what.strip().decode("utf-8")
            write_line(server, "PRIVMSG", [target, redditify(what).encode("utf-8")])
        else:
            last_lines[server, target] = msg
