#!/usr/bin/env python2

from kobunsupport import load_config, handshake, read_line, write_line

import urllib

handshake("tee tee ess")

config = load_config()


while True:
    server, prefix, command, args = read_line()

    if command.lower() == "privmsg":
        target, msg = args

        parts = msg.split(" ", 1)

        if parts[0].lower().startswith("!tts"):
            tl = parts[0][4:] or 'en_US'

            url = "http://translate.google.com/translate_tts?" + urllib.urlencode({
                'tl': tl,
                'q': parts[1],
                'ie': 'UTF-8',
            })

            write_line(server, "PRIVMSG", [target, "\x02TTS:\x02 {}".format(url)])

