#!/usr/bin/env python2

from kobunsupport import load_config, handshake, read_line, write_line, parse_prefix

import random
import time

handshake("btw u suk")

config = load_config()

TEMPLATES = [
	"btw {}",
	"ps {}",
	"{} btw",
	"just so u no {}",
	"{} just so u no",
	"{}"
]

FAGETRY = [
	"ur a faget",
	"u suk",
	"u stinx",
	"u reex",
	"ur a coq",
	"ur a dique"
]

while True:
    server, prefix, command, args = read_line()

    if command.lower() == "privmsg":
        target, msg = args

        nick, _, _ = parse_prefix(prefix)
        if nick.lower().startswith(('zor', 'alexrp')) and any(c in msg.lower() for c in [':v', ':\\/', 'v:', '\\/:']) and random.random() <= 0.8:
            time.sleep(random.randint(30, 5 * 60))
            write_line(server, "PRIVMSG", [target, "{}: {}".format(
                nick,
                random.choice(TEMPLATES).format(random.choice(FAGETRY))
            )])


