#!/usr/bin/env python2

from kobunsupport import load_config, handshake, read_line, write_line

import json
import requests
import gevent
import urllib

handshake("le cesspit")

config = load_config()


def worker(server, target, term):
    r = requests.get("http://api.urbandictionary.com/v0/define?" + urllib.urlencode({
        'term': term
    }), headers={'User-Agent': 'Mojilla/5.0'}).json()

    if r["result_type"] != "exact":
        write_line(server, "PRIVMSG", [target, "\x02UrbanDictionary:\x02 No definitions.".encode("utf-8")])
        return

    write_line(server, "PRIVMSG", [target, u"\x02UrbanDictionary:\x02 {}".format(r["list"][0]["definition"].replace("\r", "").replace("\n", " ")).encode("utf-8")])

def core():
    while True:
        server, prefix, command, args = read_line()

        if command.lower() == "privmsg":
            target, msg = args

            parts = msg.split(" ", 1)
            if parts[0].lower() == "!ud":
                gevent.spawn(worker, server, target, parts[1])

        gevent.sleep(0)

gevent.spawn(core).join()

